export const FETCH_OWNER_BEGIN = "FETCH_OWNER_BEGIN";
export const FETCH_OWNER_SUCCESS = "FETCH_OWNER_SUCCESS";
export const FETCH_OWNER_FAILURE = "FETCH_OWNER_FAILURE";

export const FETCH_FORMS_BEGIN = "FETCH_FORMS_BEGIN";
export const FETCH_FORMS_SUCCESS = "FETCH_FORMS_SUCCESS";
export const FETCH_FORMS_FAILURE = "FETCH_FORMS_FAILURE";

export const FETCH_RESPONDENTS_BEGIN = "FETCH_RESPONDENTS_BEGIN";
export const FETCH_RESPONDENTS_SUCCESS = "FETCH_RESPONDENTS_SUCCESS";
export const FETCH_RESPONDENTS_FAILURE = "FETCH_RESPONDENTS_FAILURE";

export const FETCH_APPROVER_RESPONDENTS_BEGIN =
  "FETCH_APPROVER_RESPONDENTS_BEGIN";
export const FETCH_APPROVER_RESPONDENTS_SUCCESS =
  "FETCH_APPROVER_RESPONDENTS_SUCCESS";
export const FETCH_APPROVER_RESPONDENTS_FAILURE =
  "FETCH_APPROVER_RESPONDENTS_FAILURE";

export const FETCH_RESPONDENT = "FETCH_RESPONDENT_LIST";
export const FETCH_RESPONDENT_SUCCESS = "FETCH_RESPONDENT_LIST_SUCCESS";
export const FETCH_RESPONDENT_FAILURE = "FETCH_RESPONDENT_LIST_FAILURE";
